---
abstract: 'Simple message sender for im.kayac'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  CPAN::Meta: '0'
  CPAN::Meta::Prereqs: '0'
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v0.12.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-ImKayac-Simple
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WebService::ImKayac::Simple:
    file: lib/WebService/ImKayac/Simple.pm
    version: '0.10'
requires:
  Digest::SHA1: '0'
  Encode: '2.57'
  Furl: '0'
  JSON: '0'
  YAML::Tiny: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/moznion/WebService-ImKayac-Simple/issues
  homepage: https://github.com/moznion/WebService-ImKayac-Simple
  repository: git://github.com/moznion/WebService-ImKayac-Simple.git
version: '0.10'
